name: Check Hugo build

on:
  # Runs on pushes targeting any branch and on pull requests
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.108.0
    steps:
      - name: Install Hugo CLI
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get update -y -qq
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y hugo
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare data files
        run: |
          make
      - name: Build with Hugo
        run: |
          hugo
